"""
Report generator — produces a Markdown report from a RunSummary.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from confab_test.runner import RunSummary
from confab_test.tests.base import Verdict

_ICON = {Verdict.PASS: "✓", Verdict.FAIL: "✗", Verdict.UNCERTAIN: "?", Verdict.ERROR: "!"}
_LABEL = {Verdict.PASS: "PASS", Verdict.FAIL: "FAIL", Verdict.UNCERTAIN: "UNCERTAIN", Verdict.ERROR: "ERROR"}


def generate_report(summary: RunSummary, output_dir: str) -> Path:
    """Write a Markdown report; return path to the file."""
    out_dir = Path(output_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    safe_model = summary.model.replace(":", "_").replace("/", "_")
    path = out_dir / f"{safe_model}_{ts}.md"

    lines: list[str] = []

    # Header
    lines += [
        f"# Confabulation Test Report",
        f"",
        f"**Model:** `{summary.model}`  ",
        f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}  ",
        f"**Duration:** {summary.duration:.1f}s  ",
        f"**Categories tested:** {', '.join(summary.categories)}",
        f"",
    ]

    # Summary table
    scores = summary.category_scores()
    overall = summary.overall_score()

    lines += [
        "## Summary",
        "",
        "| Category | Tests | Pass | Fail | Uncertain | Errors | Score |",
        "|----------|------:|-----:|-----:|----------:|-------:|------:|",
    ]
    for cat, s in scores.items():
        lines.append(
            f"| {cat} | {s['total']} | {s['passed']} | {s['failed']} "
            f"| {s['uncertain']} | {s['errors']} | {s['score']:.0f}% |"
        )
    lines += [
        f"| **OVERALL** | {len(summary.results)} | | | | | **{overall:.0f}%** |",
        "",
    ]

    # Confabulation fingerprint bar
    lines += [
        "## Confabulation Fingerprint",
        "",
    ]
    for cat, s in scores.items():
        bar_len = 20
        filled = int(s["score"] / 100 * bar_len)
        bar = "█" * filled + "░" * (bar_len - filled)
        lines.append(f"`{cat:30s}` `{bar}` {s['score']:.0f}%")
    lines.append("")

    # Per-category detail
    lines += ["## Detailed Results", ""]

    for cat in summary.categories:
        cat_results = [r for r in summary.results if r.category == cat]
        if not cat_results:
            continue

        cat_score = scores.get(cat, {}).get("score", 0)
        lines += [f"### {cat.replace('_', ' ').title()} ({cat_score:.0f}%)", ""]

        for r in cat_results:
            icon = _ICON[r.verdict]
            label = _LABEL[r.verdict]
            lines += [
                f"#### {icon} {label}: `{r.test_name}`",
                "",
            ]

            # Prompts
            for i, (prompt, response) in enumerate(zip(r.prompts, r.responses)):
                turn = f"Turn {i+1}" if len(r.prompts) > 1 else "Prompt"
                lines += [
                    f"**{turn}:**",
                    f"> {prompt}",
                    "",
                    f"**Response:**",
                    "```",
                    response[:600] + ("…" if len(response) > 600 else ""),
                    "```",
                    "",
                ]

            lines += [
                f"**Verdict:** {label}  ",
                f"**Reason:** {r.reason}  ",
                f"**Duration:** {r.duration:.1f}s",
                "",
            ]

            # Show metadata if interesting
            if r.metadata:
                interesting = {
                    k: v for k, v in r.metadata.items()
                    if k not in ("notes",) and v
                }
                if interesting:
                    lines += [
                        "<details><summary>Metadata</summary>",
                        "",
                        "```json",
                        json.dumps(interesting, indent=2, default=str)[:1000],
                        "```",
                        "",
                        "</details>",
                        "",
                    ]

            lines += ["---", ""]

    # Footer
    lines += [
        "## Notes",
        "",
        "- `PASS` = model behaved honestly (acknowledged limitations, correct information)",
        "- `FAIL` = model confabulated (fabricated output, false capability claim, etc.)",
        "- `UNCERTAIN` = response was ambiguous, could not determine verdict",
        "- `ERROR` = test encountered a technical error",
        "",
        f"*Generated by confab_test v0.1.0*",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generate_json_report(summary: RunSummary, output_dir: str) -> Path:
    """Write results as JSON for further analysis."""
    out_dir = Path(output_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    safe_model = summary.model.replace(":", "_").replace("/", "_")
    path = out_dir / f"{safe_model}_{ts}.json"

    data = {
        "model": summary.model,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "duration_secs": summary.duration,
        "overall_score": summary.overall_score(),
        "category_scores": summary.category_scores(),
        "results": [
            {
                "test_id": r.test_id,
                "category": r.category,
                "test_name": r.test_name,
                "verdict": r.verdict,
                "score": r.score,
                "reason": r.reason,
                "duration": r.duration,
                "prompts": r.prompts,
                "responses": r.responses,
                "metadata": r.metadata,
                "timestamp": r.timestamp.isoformat(),
            }
            for r in summary.results
        ],
    }

    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
    return path
